<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ink_document.proto

namespace Nexink\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>nexink.proto.ProtoInkDocument</code>
 */
class ProtoInkDocument extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .nexink.proto.ProtoInkStroke strokes = 1;</code>
     */
    private $strokes;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Nexink\Proto\ProtoInkStroke[] $strokes
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\InkDocument::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .nexink.proto.ProtoInkStroke strokes = 1;</code>
     * @return RepeatedField<\Nexink\Proto\ProtoInkStroke>
     */
    public function getStrokes()
    {
        return $this->strokes;
    }

    /**
     * Generated from protobuf field <code>repeated .nexink.proto.ProtoInkStroke strokes = 1;</code>
     * @param \Nexink\Proto\ProtoInkStroke[] $var
     * @return $this
     */
    public function setStrokes(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Nexink\Proto\ProtoInkStroke::class);
        $this->strokes = $arr;

        return $this;
    }

}

