<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ink_document.proto

namespace Nexink\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>nexink.proto.ProtoInkStroke</code>
 */
class ProtoInkStroke extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>repeated .nexink.proto.ProtoInkPoint points = 2;</code>
     */
    private $points;
    /**
     * Generated from protobuf field <code>float width = 3;</code>
     */
    protected $width = 0.0;
    /**
     * Generated from protobuf field <code>int32 color = 4;</code>
     */
    protected $color = 0;
    /**
     * Generated from protobuf field <code>bool is_eraser = 5;</code>
     */
    protected $is_eraser = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type \Nexink\Proto\ProtoInkPoint[] $points
     *     @type float $width
     *     @type int $color
     *     @type bool $is_eraser
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\InkDocument::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .nexink.proto.ProtoInkPoint points = 2;</code>
     * @return RepeatedField<\Nexink\Proto\ProtoInkPoint>
     */
    public function getPoints()
    {
        return $this->points;
    }

    /**
     * Generated from protobuf field <code>repeated .nexink.proto.ProtoInkPoint points = 2;</code>
     * @param \Nexink\Proto\ProtoInkPoint[] $var
     * @return $this
     */
    public function setPoints(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Nexink\Proto\ProtoInkPoint::class);
        $this->points = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float width = 3;</code>
     * @return float
     */
    public function getWidth()
    {
        return $this->width;
    }

    /**
     * Generated from protobuf field <code>float width = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setWidth(float $var)
    {
        $this->width = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 color = 4;</code>
     * @return int
     */
    public function getColor()
    {
        return $this->color;
    }

    /**
     * Generated from protobuf field <code>int32 color = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setColor(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->color = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_eraser = 5;</code>
     * @return bool
     */
    public function getIsEraser()
    {
        return $this->is_eraser;
    }

    /**
     * Generated from protobuf field <code>bool is_eraser = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsEraser(bool $var)
    {
        $this->is_eraser = $var;

        return $this;
    }

}

