<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ink_document.proto

namespace Nexink\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>nexink.proto.ProtoInkPoint</code>
 */
class ProtoInkPoint extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>float x = 1;</code>
     */
    protected $x = 0.0;
    /**
     * Generated from protobuf field <code>float y = 2;</code>
     */
    protected $y = 0.0;
    /**
     * Generated from protobuf field <code>float pressure = 3;</code>
     */
    protected $pressure = 0.0;
    /**
     * Generated from protobuf field <code>float tilt = 4;</code>
     */
    protected $tilt = 0.0;
    /**
     * Generated from protobuf field <code>float orientation = 5;</code>
     */
    protected $orientation = 0.0;
    /**
     * Generated from protobuf field <code>float velocity = 6;</code>
     */
    protected $velocity = 0.0;
    /**
     * Generated from protobuf field <code>int64 timestamp = 7;</code>
     */
    protected $timestamp = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $x
     *     @type float $y
     *     @type float $pressure
     *     @type float $tilt
     *     @type float $orientation
     *     @type float $velocity
     *     @type int|string $timestamp
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\InkDocument::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>float x = 1;</code>
     * @return float
     */
    public function getX()
    {
        return $this->x;
    }

    /**
     * Generated from protobuf field <code>float x = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setX(float $var)
    {
        $this->x = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float y = 2;</code>
     * @return float
     */
    public function getY()
    {
        return $this->y;
    }

    /**
     * Generated from protobuf field <code>float y = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setY(float $var)
    {
        $this->y = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float pressure = 3;</code>
     * @return float
     */
    public function getPressure()
    {
        return $this->pressure;
    }

    /**
     * Generated from protobuf field <code>float pressure = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setPressure(float $var)
    {
        $this->pressure = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float tilt = 4;</code>
     * @return float
     */
    public function getTilt()
    {
        return $this->tilt;
    }

    /**
     * Generated from protobuf field <code>float tilt = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setTilt(float $var)
    {
        $this->tilt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float orientation = 5;</code>
     * @return float
     */
    public function getOrientation()
    {
        return $this->orientation;
    }

    /**
     * Generated from protobuf field <code>float orientation = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setOrientation(float $var)
    {
        $this->orientation = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float velocity = 6;</code>
     * @return float
     */
    public function getVelocity()
    {
        return $this->velocity;
    }

    /**
     * Generated from protobuf field <code>float velocity = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setVelocity(float $var)
    {
        $this->velocity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 timestamp = 7;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Generated from protobuf field <code>int64 timestamp = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->timestamp = $var;

        return $this;
    }

}

