<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ink_document.proto

namespace GPBMetadata;

class InkDocument
{
    public static bool $is_initialized = false;

    public static function initOnce(): void {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\x8C\x03\x0A\x12ink_document.proto\x12\x0Cnexink.proto\"A\x0A\x10ProtoInkDocument\x12-\x0A\x07strokes\x18\x01 \x03(\x0B2\x1C.nexink.proto.ProtoInkStroke\"z\x0A\x0EProtoInkStroke\x12\x0A\x0A\x02id\x18\x01 \x01(\x09\x12+\x0A\x06points\x18\x02 \x03(\x0B2\x1B.nexink.proto.ProtoInkPoint\x12\x0D\x0A\x05width\x18\x03 \x01(\x02\x12\x0D\x0A\x05color\x18\x04 \x01(\x05\x12\x11\x0A\x09is_eraser\x18\x05 \x01(\x08\"\x7F\x0A\x0DProtoInkPoint\x12\x09\x0A\x01x\x18\x01 \x01(\x02\x12\x09\x0A\x01y\x18\x02 \x01(\x02\x12\x10\x0A\x08pressure\x18\x03 \x01(\x02\x12\x0C\x0A\x04tilt\x18\x04 \x01(\x02\x12\x13\x0A\x0Borientation\x18\x05 \x01(\x02\x12\x10\x0A\x08velocity\x18\x06 \x01(\x02\x12\x11\x0A\x09timestamp\x18\x07 \x01(\x03B \x0A\x12com.nexinkrx.protoB\x08InkProtoP\x01b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

